### ISSUE TITLE
Memory leak in test `ltc_decode_timecode_dot_raw`

### ISSUE THREAD

**Issue by icmccorm** [jmaibaum/x42ltc#1]
Valgrind reports a memory leak when running the test case `ltc_decode_timecode_dot_raw`
```
test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 2 filtered out; finished in 0.15s

       Error leaked 11.9 kiB in 1 block
        Info at calloc
             at ltc_decoder_create (vendor/src/ltc.c:42)
             at vendor_tests::decode_raw (vendor_tests.rs:31)
             at vendor_tests::ltc_decode_timecode_dot_raw (vendor_tests.rs:196)
             at vendor_tests::ltc_decode_timecode_dot_raw::{{closure}} (vendor_tests.rs:192)
             at core::ops::function::FnOnce::call_once (function.rs:250)
             at test::__rust_begin_short_backtrace
             at test::types::RunnableTest::run
             at test::run_test_in_process
             at std::sys_common::backtrace::__rust_begin_short_backtrace
             at core::ops::function::FnOnce::call_once{{vtable.shim}}
             at std::sys::unix::thread::Thread::new::thread_start
     Summary Leaked 11.9 kiB total
```

(Note: this bug was originally detected by [MiriLLI](https://github.com/icmccorm/mirilli), but we used Valgrind as a smoke check. We opted to provide the Valgrind report in this test, since this bug isn't relevant to the features that Miri is uniquely capable of detecting. The output from MiriLLI for this test is available in our dataset.)

**Comment by jmaibaum** [comment]
Thanks for your report. Since I am away from a machine where I can run valgrind, can you maybe check if #2 fixes the leak? (I created the PR on my phone.)

**Comment by jmaibaum** [comment]
Please check if this fixes it. I was not able to reproduce, even though the test was clearly missing the call to `ltc_decoder_free`.
